#!/usr/bin/env python3
"""Generate every paper table (.tex fragment) and figure (.png + provenance sidecar) from an aggregated result file
(for the final paper: results/processed/final_matrix/all_results.csv, as invoked by scripts/run_validation.sh; the default
--results value is the intermediate results/processed/legacy_v1/ output).

  python scripts/make_tables_figures.py --results results/processed/final_matrix/all_results.csv \
        --configs configs/cifar10_iid.json configs/mnist_iid.json configs/gtsrb_iid.json configs/cifar10_dirichlet.json \
        --tables-dir results/tables --figures-dir figures
Also writes <tables-dir>/table_values.json with every numeric value used in the tables (for check_paper_numbers.py).
"""
import argparse, json, os, sys, shutil
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
import pandas as pd, numpy as np
from pathlib import Path
from bpa_fu.experiment import ExperimentConfig
from bpa_fu import latex_tables as T, plotting as P

p = argparse.ArgumentParser()
p.add_argument("--results", default="results/processed/legacy_v1/all_results.csv")
p.add_argument("--resnet-results", default=None, help="processed result file of the ResNet-18 architecture check (v7)")
p.add_argument("--resnet-alignment", default=None)
p.add_argument("--resnet-config", default="configs/v7/cifar10_iid_resnet18.json")
p.add_argument("--resnet-bn", default=None, help="BatchNorm-recalibration diagnostic CSV of the ResNet-18 FedEraser checkpoints")
p.add_argument("--fedup-results", default=None, help="processed result file of the FedUP baseline (v8)")
p.add_argument("--fedup-alignment", default=None)
p.add_argument("--fedup-configs", nargs="*", default=["configs/v8/cifar10_iid_fedup_simplecnn.json", "configs/v8/cifar10_iid_fedup_resnet18.json"])
p.add_argument("--fedup-per-seed-out", default="supplement/fedup_per_seed.md")
p.add_argument("--configs", nargs="+", required=True)
p.add_argument("--tables-dir", default="results/tables")
p.add_argument("--figures-dir", default="figures")
p.add_argument("--paper-figures-dir", default="results/figures")
p.add_argument("--fesens", action="store_true", help="also build the FedEraser sensitivity table (requires the supplementary configs to be aggregated)")
p.add_argument("--alignment", default=None, help="path to alignment.csv; builds table_alignment.tex, table_energy.tex and fig_alignment.png")
p.add_argument("--subsets", default=None, help="path to attacker_subsets.csv; builds table_subsets.tex")
p.add_argument("--negphases", default=None, help="path to negation_phases.csv; builds table_negphases.tex")
p.add_argument("--fpchannels", default=None, help="path to fineprune_channels.csv; adds the Fine-Pruning channel measurement values (alpha = 1)")
a = p.parse_args()
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
df = pd.read_csv(a.results)
cfgs = [ExperimentConfig.load(c) for c in a.configs]
cfgs = [c for c in cfgs if (df.exp_id == c.exp_id).any()]
# main tables/figures use only experiments that ran the complete method set; supplementary configs (FedEraser sensitivity) are excluded
cfgs = [c for c in cfgs if {"short_retrain", "federaser", "grad_negation", "full_retrain"} <= set(c.methods)]
Path(a.tables_dir).mkdir(parents=True, exist_ok=True); Path(a.figures_dir).mkdir(parents=True, exist_ok=True); Path(a.paper_figures_dir).mkdir(parents=True, exist_ok=True)
values = {}
for name, fn, args in [("table_setup", T.table_setup, (df, cfgs)), ("table_methods", T.table_methods, (df, cfgs)),
                       ("table_fraction", T.table_fraction, (df, cfgs)), ("table_cost", T.table_cost, (df, cfgs)),
                       ("table_endpoints", T.table_endpoints, (df, cfgs)), ("table_paired_full", T.table_paired_full, (df, cfgs)),
                       ("table_endpoint_sensitivity", T.table_endpoint_sensitivity, (df, cfgs))]:
    tex, vals = fn(*args)
    header = f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.results} -- do not edit by hand\n"
    Path(a.tables_dir, name + ".tex").write_text(header + tex + "\n")
    values.update(vals)
    print("wrote", Path(a.tables_dir, name + ".tex"))
figs = [("fig_methods.png", P.fig_methods, (df, cfgs)), ("fig_fraction.png", P.fig_fraction, (df, cfgs)), ("fig_tradeoff.png", P.fig_tradeoff, (df, cfgs))]
for fname, fn, args in figs:
    out = fn(*args, Path(a.figures_dir, fname), a.results)
    if Path(a.paper_figures_dir).resolve() != Path(a.figures_dir).resolve():
        shutil.copy(out, Path(a.paper_figures_dir, fname)); shutil.copy(out.with_suffix(".provenance.json"), Path(a.paper_figures_dir, fname).with_suffix(".provenance.json"))
    print("wrote", out)
if a.fesens:
    df_all = pd.read_csv(a.results)
    tex, vals = T.table_fesens(df_all)
    Path(a.tables_dir, "table_fesens.tex").write_text(header + tex + "\n"); values.update(vals)
    d, r1, dt = (vals[f"fesens:{e}:BA"] for e in ("cifar10_iid", "cifar10_iid_federaser_r1", "cifar10_iid_federaser_dt1"))
    da, r1a, dta = (vals[f"fesens:{e}:ASR"] for e in ("cifar10_iid", "cifar10_iid_federaser_r1", "cifar10_iid_federaser_dt1"))
    sentence = (f"With the calibration ratio raised to 1 (two local epochs per stored round), BA changes from {100*d:.1f}\\% to {100*r1:.1f}\\% and ASR from {100*da:.1f}\\% to {100*r1a:.1f}\\%; "
                f"with the retaining interval lowered to 1 (updates stored every round), BA is {100*dt:.1f}\\% and ASR {100*dta:.1f}\\%.")
    Path(a.tables_dir, "fesens_sentence.tex").write_text("% AUTO-GENERATED sentence from the FedEraser sensitivity runs\n" + sentence + "\n")
    print("wrote", Path(a.tables_dir, "table_fesens.tex"))
if a.alignment:
    dfa = pd.read_csv(a.alignment)
    tex, vals = T.table_alignment(dfa, cfgs)
    Path(a.tables_dir, "table_alignment.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.alignment} -- do not edit by hand\n" + tex + "\n"); values.update(vals)
    tex, vals = T.table_energy(dfa, cfgs)
    Path(a.tables_dir, "table_energy.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.alignment} -- do not edit by hand\n" + tex + "\n"); values.update(vals)
    out = P.fig_alignment(dfa, cfgs, Path(a.figures_dir, "fig_alignment.png"), a.alignment)
    if Path(a.paper_figures_dir).resolve() != Path(a.figures_dir).resolve():
        shutil.copy(out, Path(a.paper_figures_dir, "fig_alignment.png")); shutil.copy(out.with_suffix(".provenance.json"), Path(a.paper_figures_dir, "fig_alignment.provenance.json"))
    print("wrote", Path(a.tables_dir, "table_alignment.tex"), "and", out)
if a.subsets:
    tex, vals = T.table_subsets(pd.read_csv(a.subsets))
    Path(a.tables_dir, "table_subsets.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.subsets} -- do not edit by hand\n" + tex + "\n"); values.update(vals)
if a.negphases:
    tex, vals = T.table_negation_phases(pd.read_csv(a.negphases), cfgs)
    Path(a.tables_dir, "table_negphases.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.negphases} -- do not edit by hand\n" + tex + "\n"); values.update(vals)
if a.fpchannels:
    dfp = pd.read_csv(a.fpchannels); dfp = dfp[np.isclose(dfp.alpha, 1.0)]
    values.update({"fpch:delta_pruned": float(dfp.mean_delta_pruned.mean()), "fpch:delta_kept": float(dfp.mean_delta_kept.mean()), "fpch:share_increase": float(dfp.share_trigger_increase_pruned.mean()),
                   "fpch:share_channels": float(dfp.share_channels_pruned.mean()), "fpch:top10": float(dfp.top10_trigger_channels_pruned.mean()), "fpch:n": int(len(dfp))})
if a.resnet_results:
    from bpa_fu.experiment import ExperimentConfig as _EC
    rcfg = _EC.load(a.resnet_config); dfr = pd.read_csv(a.resnet_results)
    dfra = pd.read_csv(a.resnet_alignment) if a.resnet_alignment else None
    tex, vals = T.table_resnet(dfr, dfra, rcfg)
    Path(a.tables_dir, "table_resnet18.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.resnet_results}" + (f" and {a.resnet_alignment}" if a.resnet_alignment else "") + " -- do not edit by hand\n" + tex + "\n"); values.update(vals)
    print("wrote", Path(a.tables_dir, "table_resnet18.tex"))
    if a.resnet_bn:
        dbn = pd.read_csv(a.resnet_bn)
        values.update({"rnbn:BA_stored": float(dbn.BA_stored.mean()), "rnbn:ASR_stored": float(dbn.ASR_stored.mean()), "rnbn:BA_recal": float(dbn.BA_bn_recalibrated.mean()),
                       "rnbn:ASR_recal": float(dbn.ASR_bn_recalibrated.mean()), "rnbn:BA_recal_min": float(dbn.BA_bn_recalibrated.min()), "rnbn:BA_recal_max": float(dbn.BA_bn_recalibrated.max()), "rnbn:n": int(len(dbn))})
if a.fedup_results:
    from bpa_fu.experiment import ExperimentConfig as _EC2
    fcfgs = [_EC2.load(c) for c in a.fedup_configs]; dff = pd.read_csv(a.fedup_results)
    dffa = pd.read_csv(a.fedup_alignment) if a.fedup_alignment else None
    tex, vals = T.table_fedup(dff, dffa, fcfgs)
    per_seed = vals.pop("fedup:per_seed_md")
    Path(a.tables_dir, "table_fedup.tex").write_text(f"% AUTO-GENERATED by scripts/make_tables_figures.py from {a.fedup_results}" + (f" and {a.fedup_alignment}" if a.fedup_alignment else "") + " -- do not edit by hand\n" + tex + "\n"); values.update(vals)
    Path(a.fedup_per_seed_out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.fedup_per_seed_out).write_text(f"# FedUP baseline: per-seed results (generated by scripts/make_tables_figures.py from {a.fedup_results}; do not edit)\n\nComplete identification (alpha = 1), CIFAR-10 IID, same-initialization counterfactual of the same seed. E1: ASR reduced by >= 50 pp; E2: ASR within 5 pp of the counterfactual.\n\n" + per_seed + "\n")
    print("wrote", Path(a.tables_dir, "table_fedup.tex"), "and", a.fedup_per_seed_out)
json.dump(values, open(Path(a.tables_dir, "table_values.json"), "w"), indent=2, sort_keys=True)
print("wrote", Path(a.tables_dir, "table_values.json"), len(values), "values")
