#!/usr/bin/env python3
"""Generate results/tables/numbers.tex: LaTeX macros for every number quoted in the manuscript prose.

All macros are derived from results/tables/table_values.json, which is itself generated from the
authoritative result file (results/processed/final_matrix/all_results.csv, see scripts/run_validation.sh),
so the prose can never drift from that file.
Run: python scripts/make_numbers_macros.py
"""
import argparse, json, math, os, re, sys
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
_ap = argparse.ArgumentParser(); _ap.add_argument("--values", default="results/tables/table_values.json"); _ap.add_argument("--out", default="results/tables/numbers.tex")
_args = _ap.parse_args()
vals = json.load(open(_args.values))
EXP = {"cifar10_iid": "Cifar", "mnist_iid": "Mnist", "gtsrb_iid": "Gtsrb", "cifar10_dirichlet": "CifarDir", "cifar10_iid_resnet18": "Rn"}
MET = {"before": "Before", "short_retrain": "Ft", "federaser": "Fe", "grad_negation": "Gn", "fine_pruning": "Fp", "full_retrain": "Ind", "cf_sameinit": "Cf"}
MET2 = MET
seen = set()
out = ["% AUTO-GENERATED by scripts/make_numbers_macros.py -- do not edit by hand"]

def macro(name, value, digits=1, signed=False, scale=100.0):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        s = "--"
    else:
        v = value * scale
        s = f"{v:+.{digits}f}" if signed else f"{v:.{digits}f}"
    name = re.sub(r"[^A-Za-z]", "", name)
    assert name not in seen, f"duplicate macro {name}"; seen.add(name)
    out.append(f"\\newcommand{{\\{name}}}{{{s}}}")

for exp, E in EXP.items():
    for k in ("BA", "ASR", "cfBA", "cfASR"):
        if f"setup:{exp}:{k}_mean" in vals:
            macro(f"setup{E}{k}", vals[f"setup:{exp}:{k}_mean"]); macro(f"setup{E}{k}Std", vals[f"setup:{exp}:{k}_std"])
    for m, M in MET.items():
        for k in ("BA", "ASR", "dASR", "gap"):
            key = f"methods:{exp}:{m}:{k}"
            if key in vals:
                macro(f"m{E}{M}{k}", vals[key], signed=(k in ("dASR", "gap")))
                if key + "_std" in vals:
                    macro(f"m{E}{M}{k}Std", vals[key + "_std"])
        if f"methods:{exp}:{m}:BPR" in vals:
            macro(f"m{E}{M}BPR", vals[f"methods:{exp}:{m}:BPR"], digits=2, scale=1.0)
            _b = vals[f"methods:{exp}:{m}:BPR"]
            macro(f"m{E}{M}Removedpct", None if (_b is None or (isinstance(_b, float) and math.isnan(_b))) else 1 - _b, digits=0)
            macro(f"m{E}{M}BPRpct", _b, digits=0)
        if f"fraction:{exp}:{m}:V" in vals:
            macro(f"fr{E}{M}V", vals[f"fraction:{exp}:{m}:V"], digits=2); macro(f"fr{E}{M}Tau", vals[f"fraction:{exp}:{m}:tau"])
        for a, A in (("0.25", "Quarter"), ("0.5", "Half"), ("0.75", "ThreeQ"), ("1", "Full")):
            if f"fraction:{exp}:{m}:{a}:ASR" in vals:
                macro(f"fr{E}{M}{A}ASR", vals[f"fraction:{exp}:{m}:{a}:ASR"])
                macro(f"fr{E}{M}{A}BA", vals[f"fraction:{exp}:{m}:{a}:BA"])
        if f"cost:{exp}:{m}:rel" in vals:
            macro(f"cost{E}{M}Rel", vals[f"cost:{exp}:{m}:rel"], digits=0); macro(f"cost{E}{M}Sec", vals[f"cost:{exp}:{m}:sec"], digits=0, scale=1.0)
        for e, EE in (("E1", "One"), ("E2", "Two")):
            if f"endpoints:{exp}:{m}:{e}" in vals:
                macro(f"ep{E}{M}{EE}", vals[f"endpoints:{exp}:{m}:{e}"], digits=0)
# cross-dataset aggregates used in the abstract: min/max over the three IID datasets
def agg(fn, pattern, name, exps=("cifar10_iid", "mnist_iid", "gtsrb_iid"), **kw):
    xs = [vals[pattern.format(exp=e)] for e in exps if pattern.format(exp=e) in vals]
    xs = [x for x in xs if not (isinstance(x, float) and math.isnan(x))]
    if xs:
        macro(name, fn(xs), **kw)
for m, M in MET.items():
    if m == "before":
        continue
    agg(min, "methods:{exp}:" + m + ":ASR", f"min{M}ASR"); agg(max, "methods:{exp}:" + m + ":ASR", f"max{M}ASR")
    agg(min, "methods:{exp}:" + m + ":BPR", f"min{M}BPR", digits=2, scale=1.0); agg(max, "methods:{exp}:" + m + ":BPR", f"max{M}BPR", digits=2, scale=1.0)
    agg(min, "methods:{exp}:" + m + ":dASR", f"min{M}dASR"); agg(max, "methods:{exp}:" + m + ":dASR", f"max{M}dASR")
    agg(min, "methods:{exp}:" + m + ":BPR", f"min{M}BPRpct", digits=0); agg(max, "methods:{exp}:" + m + ":BPR", f"max{M}BPRpct", digits=0)
    _ALL = ("cifar10_iid", "mnist_iid", "gtsrb_iid", "cifar10_dirichlet")
    agg(min, "methods:{exp}:" + m + ":BPR", f"min{M}BPRpctAll", exps=_ALL, digits=0); agg(max, "methods:{exp}:" + m + ":BPR", f"max{M}BPRpctAll", exps=_ALL, digits=0)
    agg(min, "methods:{exp}:" + m + ":ASR", f"min{M}ASRAll", exps=_ALL); agg(max, "methods:{exp}:" + m + ":ASR", f"max{M}ASRAll", exps=_ALL)
    agg(lambda xs: 1 - max(xs), "methods:{exp}:" + m + ":BPR", f"min{M}Removedpct", digits=0); agg(lambda xs: 1 - min(xs), "methods:{exp}:" + m + ":BPR", f"max{M}Removedpct", digits=0)
    agg(min, "methods:{exp}:" + m + ":gap", f"min{M}Gap", signed=True); agg(max, "methods:{exp}:" + m + ":gap", f"max{M}Gap", signed=True)
    agg(max, "fraction:{exp}:" + m + ":V", f"max{M}V", digits=2)
    agg(max, "cost:{exp}:" + m + ":rel", f"max{M}CostRel", digits=0); agg(min, "cost:{exp}:" + m + ":rel", f"min{M}CostRel", digits=0)
agg(min, "setup:{exp}:ASR_mean", "minBeforeASR"); agg(max, "setup:{exp}:ASR_mean", "maxBeforeASR")
agg(min, "setup:{exp}:BA_mean", "minBeforeBA"); agg(max, "setup:{exp}:BA_mean", "maxBeforeBA")
agg(max, "setup:{exp}:cfASR_mean", "maxSetupCfASR"); agg(min, "setup:{exp}:cfASR_mean", "minSetupCfASR")
ALK = {"global_cos_u_negdm": "CosNeg", "global_rho": "Kappa", "global_resid_frac": "Resid", "global_cos_u_dr": "CosRet", "global_cos_u_d": "CosD", "global_rel_dist_cf": "RelAll", "conv2_rel_dist_cf": "RelConvB", "fc1_rel_dist_cf": "RelFcA", "asr_reduction": "dASR", "u_norm": "Unorm", "conv1_energy": "EnConvA", "conv2_energy": "EnConvB", "fc1_energy": "EnFcA", "fc2_energy": "EnFcB"}
for k, v in vals.items():
    if k.startswith("align:spearman:"):
        parts = k.split(":"); nm = "alSp" + "".join(w.capitalize() for w in parts[2:]).replace("_", "")
        macro(nm, v, digits=(0 if (parts[-1] == "n" or parts[-1].endswith("_n")) else 2), scale=1.0)
    elif k.startswith("align:"):
        _, exp, met, c = k.split(":")
        E2 = {"cifar10_iid": "Cifar", "mnist_iid": "Mnist", "gtsrb_iid": "Gtsrb", "cifar10_dirichlet": "CifarDir", "cifar10_iid_federaser_r1": "CifarRone", "cifar10_iid_federaser_dt1": "CifarDtone", "cifar10_iid_resnet18": "Rn"}[exp]
        base = c.replace("_std", "").replace("_ci", "")
        if base not in ALK: continue
        suffix = "Std" if c.endswith("_std") else ("Ci" if c.endswith("_ci") else "")
        macro(f"al{E2}{MET2[met]}{ALK[base]}{suffix}", v, digits=(1 if base == "asr_reduction" else 2), scale=(100.0 if base == "asr_reduction" else 1.0), signed=(base == "asr_reduction" and suffix == ""))
def _E(exp):
    return {"cifar10_iid": "Cifar", "mnist_iid": "Mnist", "gtsrb_iid": "Gtsrb", "cifar10_dirichlet": "CifarDir", "cifar10_iid_federaser_r1": "CifarRone", "cifar10_iid_federaser_dt1": "CifarDtone", "cifar10_iid_resnet18": "Rn"}[exp]
for k, v in vals.items():
    parts = k.split(":")
    if k.startswith("paired:") and parts[-1] in ("largest_mean", "largest_lo", "largest_hi"):
        macro(f"pd{_E(parts[1])}{MET2[parts[2]]}{parts[3].split('_')[1].capitalize()}", v, digits=1, signed=True)
    elif k.startswith("paired:") and parts[-1] == "largest_pair":
        out.append(f"\\newcommand{{\\pd{_E(parts[1])}{MET2[parts[2]]}Pair}}{{{v}}}")
    elif k.startswith("epsens:"):
        _W = {"0.3": "Thirty", "0.5": "Fifty", "0.7": "Seventy", "0.02": "Two", "0.05": "Five", "0.1": "Ten"}
        macro(f"es{MET2[parts[1]]}{'One' if parts[2] == 'E1' else 'Two'}{_W[parts[3]]}", v, digits=0)
    elif k.startswith("subset:") and parts[-1] in ("nested", "mean", "min", "max", "range"):
        _K = {"1": "One", "2": "Two", "3": "Three", "4": "Four"}
        macro(f"sub{_E(parts[1])}{MET2[parts[2]]}{_K[parts[3]]}{parts[4].capitalize()}", v, digits=1)
    elif k.startswith("negphase:"):
        macro(f"np{_E(parts[1])}{parts[2].replace('_', '')}", v, digits=(0 if parts[2] == "reproduced" else 1), scale=100.0)
    elif k.startswith("energy:"):
        _L = {"conv1": "ConvA", "conv2": "ConvB", "fc1": "FcA", "fc2": "FcB", "stem": "Stem", "layer1": "LayerA", "layer2": "LayerB", "layer3": "LayerC", "layer4": "LayerD", "fc": "Fc"}
        macro(f"en{_E(parts[1])}{MET2[parts[2]]}{_L[parts[3]]}", v, digits=2, scale=1.0)
if "fpch:delta_pruned" in vals:
    macro("fpDeltaPruned", vals["fpch:delta_pruned"], digits=4, scale=1.0); macro("fpDeltaKept", vals["fpch:delta_kept"], digits=4, scale=1.0)
    macro("fpShareIncrease", vals["fpch:share_increase"], digits=0); macro("fpSharePruned", vals["fpch:share_channels"], digits=0); macro("fpTopTen", vals["fpch:top10"], digits=1, scale=1.0)
for k, v in vals.items():
    if k.startswith("fedup:"):
        _, exp, c = k.split(":"); E3 = {"cifar10_iid": "Cifar", "cifar10_iid_resnet18": "Rn"}[exp]
        base = c.replace("_std", "").replace("_cilo", "").replace("_cihi", ""); suf = "Std" if c.endswith("_std") else ("CiLo" if c.endswith("_cilo") else ("CiHi" if c.endswith("_cihi") else ""))
        if base in ("BA", "ASR", "dASR", "gap"):
            macro(f"fu{E3}{base}{suf}", v, signed=(base in ("dASR", "gap") and suf == ""))
        elif base == "BPR":
            macro(f"fu{E3}BPR{suf}", v, digits=2, scale=1.0)
        elif base == "sec":
            macro(f"fu{E3}Sec{suf}", v, digits=0, scale=1.0)
        elif base in ("E1", "E2"):
            macro(f"fu{E3}{'EOne' if base == 'E1' else 'ETwo'}", v, digits=0)
        elif base == "storage_mb":
            macro(f"fu{E3}StorageMB", v, digits=0, scale=1.0)
        elif base == "maxgap":
            macro(f"fu{E3}MaxGap", v, signed=True)
        elif base == "maxbpr":
            macro(f"fu{E3}MaxBPR", v, digits=2, scale=1.0)
        elif base == "n":
            macro(f"fu{E3}N", v, digits=0, scale=1.0)
        elif base in ALK:
            macro(f"fu{E3}{ALK[base]}{suf}", v, digits=2, scale=1.0)
if "rnbn:BA_recal" in vals:
    macro("rnBnBAStored", vals["rnbn:BA_stored"]); macro("rnBnBARecal", vals["rnbn:BA_recal"]); macro("rnBnASRRecal", vals["rnbn:ASR_recal"])
    macro("rnBnBARecalMin", vals["rnbn:BA_recal_min"]); macro("rnBnBARecalMax", vals["rnbn:BA_recal_max"]); macro("rnBnN", vals["rnbn:n"], digits=0, scale=1.0)
for k, v in vals.items():
    if k.startswith("fesens:"):
        _, exp, met = k.split(":"); macro("fes" + {"cifar10_iid": "Default", "cifar10_iid_federaser_r1": "Rone", "cifar10_iid_federaser_dt1": "Dtone"}[exp] + met, v)
open(_args.out, "w").write("\n".join(out) + "\n")
print(f"wrote {_args.out} with {len(out) - 1} macros")
