#!/usr/bin/env python3
"""Generate results/tables/pilot_numbers.tex (macros \\pg...) from the v7 validation-split pilot records, applying the
pre-registered Rules G and R of audit/v7_hyperparameter_selection_protocol.md. Also writes
results/raw/pilots_hyperparameter_selection/rule_R_selection.json when the ResNet-18 pilot records exist. Deterministic; never reads test-set values.
"""
import argparse, json, os, sys
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
p = argparse.ArgumentParser(); p.add_argument("--out", default="results/tables/pilot_numbers.tex"); p.add_argument("--allow-missing-resnet", action="store_true"); a = p.parse_args()
out = ["% AUTO-GENERATED by scripts/v7/make_pilot_macros.py from results/raw/pilots_hyperparameter_selection (validation split only) -- do not edit by hand"]
def macro(n, v): out.append(f"\\newcommand{{\\{n}}}{{{v}}}")
# Rule G
g = json.load(open("results/raw/pilots_hyperparameter_selection/negation_validation_sweep_simplecnn_selection.json"))
import csv
rows = list(csv.DictReader(open("results/raw/pilots_hyperparameter_selection/negation_validation_sweep_simplecnn.csv")))
sel = g["selected_multiplier"]; ft = [r for r in rows if r["setting"] == "fine_tuning_reference"][0]
sr = [r for r in rows if r["setting"] == "grad_negation" and float(r["threshold_mult"]) == sel][0]
assert sr["eval_split"] == "validation" and ft["eval_split"] == "validation"
macro("pgNegSelMult", f"{sel:g}"); macro("pgNegValFtBA", f"{100*float(ft['val_BA']):.1f}"); macro("pgNegValFtASR", f"{100*float(ft['val_ASR']):.1f}")
macro("pgNegValSelBA", f"{100*float(sr['val_BA']):.1f}"); macro("pgNegValSelASR", f"{100*float(sr['val_ASR']):.1f}")
# Rule R
res = {}
for tag, lr in (("lr0p01", 0.01), ("lr0p05", 0.05)):
    f = f"results/raw/pilots_hyperparameter_selection/pilot_resnet18_{tag}/seed100/compromised.json"
    if os.path.exists(f):
        r = json.load(open(f))
        if r.get("status") == "completed":
            assert r["eval_split"] == "validation", f
            res[lr] = r
if len(res) == 2:
    final = {lr: [t for t in r["trajectory"] if t["round"] == r["history_rounds"][-1] + 1 or t["round"] == 30][-1]["BA"] for lr, r in res.items()}
    lr_sel = max(final, key=final.get)
    traj = res[lr_sel]["trajectory"]; best = max(t["BA"] for t in traj)
    T_sel = min((t["round"] for t in traj if t["round"] % 2 == 0 and t["BA"] >= best - 0.01), default=30)
    val_at_T = [t for t in traj if t["round"] == T_sel][0]
    sel_r = {"rule": "Rule R: lr with higher validation BA at round 30; T = smallest even round with validation BA within 1.0 pp of the maximum over rounds <= 30",
             "validation_BA_at_30": final, "selected_lr": lr_sel, "max_validation_BA": best, "selected_T": T_sel, "validation_BA_at_T": val_at_T["BA"], "validation_ASR_at_T": val_at_T["ASR"],
             "eval_split": "validation", "pilot_seed": 100}
    json.dump(sel_r, open("results/raw/pilots_hyperparameter_selection/rule_R_selection.json", "w"), indent=2)
    macro("pgRnLr", f"{lr_sel:g}"); macro("pgRnRounds", str(T_sel)); macro("pgRnValBA", f"{100*val_at_T['BA']:.1f}"); macro("pgRnValASR", f"{100*val_at_T['ASR']:.1f}")
    for lr, v in final.items():
        macro("pgRnValBAThirty" + ("Low" if lr == 0.01 else "High"), f"{100*v:.1f}")
    ng = "results/raw/pilots_hyperparameter_selection/negation_validation_sweep_resnet18_selection.json"
    if os.path.exists(ng):
        macro("pgRnNegSelMult", f"{json.load(open(ng))['selected_multiplier']:g}")
    elif a.allow_missing_resnet:
        macro("pgRnNegSelMult", "PLACEHOLDER")
    else:
        sys.exit("ResNet negation selection missing")
elif a.allow_missing_resnet:
    for n in ("pgRnLr", "pgRnRounds", "pgRnValBA", "pgRnValASR", "pgRnNegSelMult"):
        macro(n, "PLACEHOLDER")
else:
    sys.exit("ResNet-18 pilot records missing")
# v8: FedUP pruning-percentage sensitivity on the validation split (robustness check; not a selection)
for tag, E in (("simplecnn", "Cnn"), ("resnet18", "Rn")):
    f = f"results/raw/pilots_fedup_sensitivity/fedup_sensitivity_{tag}.csv"
    if os.path.exists(f):
        rows = list(csv.DictReader(open(f))); assert all(r["eval_split"] == "validation" for r in rows)
        ft = [r for r in rows if r["setting"] == "fine_tuning_reference"][0]
        macro(f"pgFu{E}FtValBA", f"{100*float(ft['val_BA']):.1f}"); macro(f"pgFu{E}FtValASR", f"{100*float(ft['val_ASR']):.1f}")
        for r in rows:
            if r["setting"] == "fedup":
                P = {"0.05": "Five", "0.1": "Ten", "0.2": "Twenty"}[r["prune_fraction"]]
                macro(f"pgFu{E}{P}ValBA", f"{100*float(r['val_BA']):.1f}"); macro(f"pgFu{E}{P}ValASR", f"{100*float(r['val_ASR']):.1f}")
open(a.out, "w").write("\n".join(out) + "\n"); print("wrote", a.out, len(out) - 1, "macros")
